# Generated by Django 5.1.2 on 2024-10-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='defaults/cover.jpeg', upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='defaults/profile.jpeg', upload_to='profile_images/'),
        ),
    ]
